# Generated by Django 4.1.4 on 2022-12-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlesscopes_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
    ]
